#Name of the application
spring:
  application:
    name: ZuulService

#Eureka server url for registering
#This is eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#register url to server    
  
server:
  port: 8989
  
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  prefix: /productportal
  routes:
    product-details-service:
      path: /productdetailsservice/**
      service-id: product-details-service
    product-service:
      path: /productservice/**
      service-id: product-service
    inventory-service:
      path: /inventoryservice/**
      service-id: inventory-service
     
     
      